### PR TITLE
Added old classic

### PR DESCRIPTION
**Pull request by BloodRedTape**
- Added gaysex deck
   - Added Duo pattern
   - Added 911 pattern
   - Added Cooperative pattern

### CODE REVIEW

**Review by novosaleks — APPROVED** [review]

**Comment by eternityduck** [comment]
🚀 Wow! This feature is absolutely thrilling! 🎉 I'm beyond excited about the incredible value it brings to our project. The functionality, usability, and overall impact are simply outstanding. It's clear that a tremendous amount of thought, effort, and expertise went into crafting this addition. I can't wait to see how it enhances our project and benefits our users. Phenomenal work! 🔥 Let's merge this in and watch our project soar to new heights! 🚀🚀🚀

**Comment by eddienubes** [comment]
No way! This deck will bring so much gameplay! I'm so excited! 
Please approve!!!

**Comment by eddienubes** [comment]
Thank you!

**Comment by nikita-nikita-nikita** [comment]
Lgtm, the fastest approve I ever did

**Comment by zagorboda** [comment]
LGTM

**Comment by zagorboda** [comment]
lgtm

**Pull request merged**
